# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe531872637a893288757b82538b405dc2624f4f7962da77cc91bddfd2fc4711ebaab867d3dca33fbd0e2b674ac2d7e5c3e8bb72f45846d159dfa4f7cba58c1

test:
  secret_key_base: fb007c20827b6b01a8cd79efbceea87f454e60ae016010bf4ecc6882b9cc40695454c62d6eb5e31fe9e41e964c630908b26165494a1db448e7b121f573fa5f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
